config/routes.rb
Examen::Application.routes.draw do
  resources :allowed_packages

  resources :package_items

  resources :clients

  resources :agreements

  resources :packages

  root :to => "clients#new"

end

app/models/package_item.rb
class PackageItem < ActiveRecord::Base

  belongs_to :package
  STATES = ["En Stock", "Asignado", "Mantenimiento", "Devuelto"]

  def mark_as_assigned
    self.state = STATES[1]
    self.save
  end

end

app/controllers/package_items_controller.rb
class PackageItemsController < ApplicationController
  # GET /package_items
  # GET /package_items.json
  def index
    @package_items = PackageItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @package_items }
    end
  end

  # GET /package_items/1
  # GET /package_items/1.json
  def show
    @package_item = PackageItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @package_item }
    end
  end

  # GET /package_items/new
  # GET /package_items/new.json
  def new
    @package_item = PackageItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @package_item }
    end
  end

  # GET /package_items/1/edit
  def edit
    @package_item = PackageItem.find(params[:id])
  end

  # POST /package_items
  # POST /package_items.json
  def create
    @package_item = PackageItem.new(params[:package_item])

    respond_to do |format|
      if @package_item.save
        format.html { redirect_to @package_item, notice: 'Package item was successfully created.' }
        format.json { render json: @package_item, status: :created, location: @package_item }
      else
        format.html { render action: "new" }
        format.json { render json: @package_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /package_items/1
  # PUT /package_items/1.json
  def update
    @package_item = PackageItem.find(params[:id])

    respond_to do |format|
      if @package_item.update_attributes(params[:package_item])
        format.html { redirect_to @package_item, notice: 'Package item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @package_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /package_items/1
  # DELETE /package_items/1.json
  def destroy
    @package_item = PackageItem.find(params[:id])
    @package_item.destroy

    respond_to do |format|
      format.html { redirect_to package_items_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/package_items_helper.rb
module PackageItemsHelper
end

app/views/package_items/_form.html.erb
<%= simple_form_for(@package_item) do |f| %>
  <% if @package_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@package_item.errors.count, "error") %> prohibited this package_item from being saved:</h2>

      <ul>
      <% @package_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.association :package, :label => "Tipo", :label_method => "kind" %>
  </div>
  <div class="field">
    <%= f.input :state, :collection => PackageItem::STATES %>
  </div>
  <div class="field">
    <%= f.association :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/package_items/edit.html.erb
<h1>Editing package_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @package_item %> |
<%= link_to 'Back', package_items_path %>

app/views/package_items/index.html.erb
<h1>Listing package_items</h1>

<table>
  <tr>
    <th>Package</th>
    <th>State</th>
    <th>Agreement</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @package_items.each do |package_item| %>
  <tr>
    <td><%= package_item.package_id %></td>
    <td><%= package_item.state %></td>
    <td><%= package_item.agreement_id %></td>
    <td><%= link_to 'Show', package_item %></td>
    <td><%= link_to 'Edit', edit_package_item_path(package_item) %></td>
    <td><%= link_to 'Destroy', package_item, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Package item', new_package_item_path %>

app/views/package_items/new.html.erb
<h1>New package_item</h1>

<%= render 'form' %>

<%= link_to 'Back', package_items_path %>

app/views/package_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Package:</b>
  <%= @package_item.package_id %>
</p>

<p>
  <b>State:</b>
  <%= @package_item.state %>
</p>

<p>
  <b>Agreement:</b>
  <%= @package_item.agreement_id %>
</p>


<%= link_to 'Edit', edit_package_item_path(@package_item) %> |
<%= link_to 'Back', package_items_path %>