config/routes.rb
Examen::Application.routes.draw do
  resources :allowed_packages

  resources :package_items

  resources :clients

  resources :agreements

  resources :packages

  root :to => "clients#new"

end

app/models/allowed_package.rb
class AllowedPackage < ActiveRecord::Base
  belongs_to :client
  belongs_to :package
end

app/controllers/allowed_packages_controller.rb
class AllowedPackagesController < ApplicationController
  # GET /allowed_packages
  # GET /allowed_packages.json
  def index
    @allowed_packages = AllowedPackage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @allowed_packages }
    end
  end

  # GET /allowed_packages/1
  # GET /allowed_packages/1.json
  def show
    @allowed_package = AllowedPackage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @allowed_package }
    end
  end

  # GET /allowed_packages/new
  # GET /allowed_packages/new.json
  def new
    @allowed_package = AllowedPackage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @allowed_package }
    end
  end

  # GET /allowed_packages/1/edit
  def edit
    @allowed_package = AllowedPackage.find(params[:id])
  end

  # POST /allowed_packages
  # POST /allowed_packages.json
  def create
    @allowed_package = AllowedPackage.new(params[:allowed_package])

    respond_to do |format|
      if @allowed_package.save
        format.html { redirect_to @allowed_package, notice: 'Allowed package was successfully created.' }
        format.json { render json: @allowed_package, status: :created, location: @allowed_package }
      else
        format.html { render action: "new" }
        format.json { render json: @allowed_package.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /allowed_packages/1
  # PUT /allowed_packages/1.json
  def update
    @allowed_package = AllowedPackage.find(params[:id])

    respond_to do |format|
      if @allowed_package.update_attributes(params[:allowed_package])
        format.html { redirect_to @allowed_package, notice: 'Allowed package was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @allowed_package.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /allowed_packages/1
  # DELETE /allowed_packages/1.json
  def destroy
    @allowed_package = AllowedPackage.find(params[:id])
    @allowed_package.destroy

    respond_to do |format|
      format.html { redirect_to allowed_packages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/allowed_packages_helper.rb
module AllowedPackagesHelper
end

app/views/allowed_packages/_form.html.erb
<%= form_for(@allowed_package) do |f| %>
  <% if @allowed_package.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@allowed_package.errors.count, "error") %> prohibited this allowed_package from being saved:</h2>

      <ul>
      <% @allowed_package.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :client_id %><br />
    <%= f.number_field :client_id %>
  </div>
  <div class="field">
    <%= f.label :package_id %><br />
    <%= f.number_field :package_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/allowed_packages/edit.html.erb
<h1>Editing allowed_package</h1>

<%= render 'form' %>

<%= link_to 'Show', @allowed_package %> |
<%= link_to 'Back', allowed_packages_path %>

app/views/allowed_packages/index.html.erb
<h1>Listing allowed_packages</h1>

<table>
  <tr>
    <th>Client</th>
    <th>Package</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @allowed_packages.each do |allowed_package| %>
  <tr>
    <td><%= allowed_package.client_id %></td>
    <td><%= allowed_package.package_id %></td>
    <td><%= link_to 'Show', allowed_package %></td>
    <td><%= link_to 'Edit', edit_allowed_package_path(allowed_package) %></td>
    <td><%= link_to 'Destroy', allowed_package, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Allowed package', new_allowed_package_path %>

app/views/allowed_packages/new.html.erb
<h1>New allowed_package</h1>

<%= render 'form' %>

<%= link_to 'Back', allowed_packages_path %>

app/views/allowed_packages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Client:</b>
  <%= @allowed_package.client_id %>
</p>

<p>
  <b>Package:</b>
  <%= @allowed_package.package_id %>
</p>


<%= link_to 'Edit', edit_allowed_package_path(@allowed_package) %> |
<%= link_to 'Back', allowed_packages_path %>