config/routes.rb
Examen::Application.routes.draw do
  resources :allowed_packages

  resources :package_items

  resources :clients

  resources :agreements

  resources :packages

  root :to => "clients#new"

end

app/models/agreement.rb
# encoding: UTF-8
class Agreement < ActiveRecord::Base
  belongs_to :client
  belongs_to :package

  validates_presence_of :starting_at, :ending_at, :quantity, :client_id, :package_id
  validate :business_rules
  
  after_create :update_stocks
  def kind
    if less_than_year?
      "Marco"
    else
      "Locales"
    end
  end

  def update_stocks
    client.reduce_stock(self.quantity) if client
    update_items
  end

  def update_items
    self.quantity.times do
      item = self.package.package_items.create
      item.mark_as_assigned
    end
  end

  def business_rules
    if more_packages_than_allowed?
      errors.add :base, "Elegió más paquetes de los que tiene permitidos." 
    end

    if package_kind_not_allowed?
      errors.add :base, "El tipo de paquete no está disponble para este cliente" 
    end

    if incongruent_dates?
      errors.add :base, "La fecha de inicio no puede ser mayor a la final"
    end

    if shorter_than_allowed?
      errors.add :base, "El periodo debe ser mayor a dos meses"
    end
  end

  def more_packages_than_allowed?
    return false unless client
    self.client.max_allowed_packages < self.quantity
  end

  def incongruent_dates?
    self.starting_at > self.ending_at
  end

  def shorter_than_allowed?
    period < 2.months
  end

  def package_kind_not_allowed?
    return false unless client
    !self.client.packages.include? self.package
  end

  def period
    self.ending_at - self.starting_at
  end

  def less_than_year?
    period < 1.year
  end

end

app/controllers/agreements_controller.rb
class AgreementsController < ApplicationController
  # GET /agreements
  # GET /agreements.json
  def index
    @agreements = Agreement.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @agreements }
    end
  end

  # GET /agreements/1
  # GET /agreements/1.json
  def show
    @agreement = Agreement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @agreement }
    end
  end

  # GET /agreements/new
  # GET /agreements/new.json
  def new
    @agreement = Agreement.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @agreement }
    end
  end

  # GET /agreements/1/edit
  def edit
    @agreement = Agreement.find(params[:id])
  end

  # POST /agreements
  # POST /agreements.json
  def create
    @agreement = Agreement.new(params[:agreement])

    respond_to do |format|
      if @agreement.save

        format.html { redirect_to @agreement, notice: 'Agreement was successfully created.' }
        format.json { render json: @agreement, status: :created, location: @agreement }
      else
        format.html { render action: "new" }
        format.json { render json: @agreement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /agreements/1
  # PUT /agreements/1.json
  def update
    @agreement = Agreement.find(params[:id])

    respond_to do |format|
      if @agreement.update_attributes(params[:agreement])
        format.html { redirect_to @agreement, notice: 'Agreement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @agreement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agreements/1
  # DELETE /agreements/1.json
  def destroy
    @agreement = Agreement.find(params[:id])
    @agreement.destroy

    respond_to do |format|
      format.html { redirect_to agreements_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/agreements_helper.rb
module AgreementsHelper
end

app/views/agreements/_form.html.erb
<%= simple_form_for(@agreement) do |f| %>
  <% if @agreement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agreement.errors.count, "error") %> prohibited this agreement from being saved:</h2>

      <ul>
      <% @agreement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.association :client %>
  </div>


  <div class="field">
    <%= f.label :starting_at %><br />
    <%= f.datetime_select :starting_at %>
  </div>
  <div class="field">
    <%= f.label :ending_at %><br />
    <%= f.datetime_select :ending_at %>
  </div>
  <div class="field">
    <%= f.association :package, :label => "Kind", :label_method => "kind" %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/agreements/edit.html.erb
<h1>Editing agreement</h1>

<%= render 'form' %>

<%= link_to 'Show', @agreement %> |
<%= link_to 'Back', agreements_path %>

app/views/agreements/index.html.erb
<h1>Listing agreements</h1>

<table>
  <tr>
    <th>Starting at</th>
    <th>Ending at</th>
    <th>Kind</th>
    <th>Quantity</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @agreements.each do |agreement| %>
  <tr>
    <td><%= agreement.starting_at %></td>
    <td><%= agreement.ending_at %></td>
    <td><%= agreement.kind %></td>
    <td><%= agreement.quantity %></td>
    <td><%= link_to 'Show', agreement %></td>
    <td><%= link_to 'Edit', edit_agreement_path(agreement) %></td>
    <td><%= link_to 'Destroy', agreement, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Agreement', new_agreement_path %>

app/views/agreements/new.html.erb
<h1>New agreement</h1>

<%= render 'form' %>

<%= link_to 'Back', agreements_path %>

app/views/agreements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Starting at:</b>
  <%= @agreement.starting_at %>
</p>

<p>
  <b>Ending at:</b>
  <%= @agreement.ending_at %>
</p>

<p>
  <b>Tipo:</b>
  <%= @agreement.package.kind %>
</p>


<p>
  <b>Kind:</b>
  Contrato <%= @agreement.kind %>
</p>

<p>
  <b>Quantity:</b>
  <%= @agreement.quantity %>
</p>


<%= link_to 'Edit', edit_agreement_path(@agreement) %> |
<%= link_to 'Back', agreements_path %>